---

- hosts: all
  become: yes 
  tasks:
  - name: Install Apache Packages
    apt: name=apache2 state=present

  - name: Start Apache Service 
    service: name=apache2 state=started

  - name: Deploy Custom Info file
    copy: src=templates/info.html dest=/var/www/html/info.html
